### ISSUE TITLE
what python version to use

### ISSUE THREAD

**Issue by ghost** [MaciekBaron/lastfm-bio-scraper#1]
hi,

before i found your useful software of which i think that it will fit my needs because it was outlined on reddit.com i did previous research on album art and foobar2000 and that finally redirects my to your project, i heard of requests a http library serving requests in many popular projects and of course your project, but hey my question is which python version should i use because i had trouble before on windows with python regarding 32bit or should i use 64bit, the version is not the problem 2.7 should be fair in many projects nowadays, i have linux experience and though python and or similar languages but pip comes not preinstalled when installing python on windows, i have found get-pip.py but windows makes it difficult for me to install requests using pip on windows 10 64bit pro edition, can you provide install instructions so i can use the extension for foobar2000 thanks Fikret

**Comment by MaciekBaron** [comment]
Hi. Python 2.7.9 should come with [pep preinstalled](https://docs.python.org/2/whatsnew/2.7.html#pep-477-backport-ensurepip-pep-453-to-python-2-7). Try that version and see if it works. You can also find some more detailed instructions for older versions [here](http://stackoverflow.com/questions/4750806/how-do-i-install-pip-on-windows). Hope this helps.

**Comment by ghost** [comment]
everything ok, but i cant see biography anywhere, the only thing i did i pointed to script.py and hit add i downloaded biography from http://foo2k.chottu.net/ is this wrong, thanks

**Comment by ghost** [comment]
![noname](https://cloud.githubusercontent.com/assets/11350782/12697662/8d7921f4-c789-11e5-849d-9d48c56cd37f.png) Biography Window looks like this this is different from yours i think thats where the error stems from

**Comment by MaciekBaron** [comment]
You need to move the "Run External Script" item to the left, so that is is above Last.fm. You can use `<<` to move it left and then `Up` and `Down` to move it... up and down ;) Hope this helps!

**Comment by ghost** [comment]
thanks for replying, still it has the same layout as attached before, where is the switch to activate biography in case it works, thats what i am wondering too, but nice project, even if i still have no success.

**Comment by MaciekBaron** [comment]
If you haven't used the actual plugin before, you need to enable it in your actual layout. I don't know what you're using for you interface (I use ColumnsUI) but you need to actually display the biography pane within your layout. Have a look online how to add and remove panes in Foobar2000.
