### ISSUE TITLE
Broken, needs an update.

### ISSUE THREAD

**Issue by celroid** [MaciekBaron/lastfm-bio-scraper#2]
I don't know if it used to work, but it doesn't work for me
And I think you made a mistake in the readme file.

> As "Command line" enter python C:/SCRIPT_LOCATION/script.py "%artist%", replacing SCRIPT_LOCATION with, well.. your script's location

Windows uses C:\ not C:/
like C:\Program Files (x86)\foobar2000
Changing that however doesn't seem to make the script work.

**Comment by MaciekBaron** [comment]
No, that's not a mistake. Windows can use both.

Try putting the script in a different location, or wrapping the path in quotation marks. Perhaps the spaces in the path are causing issues.

**Comment by celroid** [comment]
I've tried multiple things.

> python "C:\Program Files '('x86')'\foobar2000\skins\lastfm-bio-scraper-master\script.py" "%artist%"
> Changed the location, with quotes
> python "C:/MyPythonScripts/script.py" "%artist%"
> without quotes
> python C:/MyPythonScripts/script.py "%artist%"
> https://gyazo.com/6424a901c8f3e26a283bdd36f714c502

I don't know how the script works but are you sure it still does get the information from last.fm? Maybe an update they did broke it.

Edit: one thing i have to mention is that I have both python 3 and 2.7 installed, Maybe it doesn't work because python 3 is set by default, know how I could get around that?

Edit2: created a symbolic link for python 2.7 

> python27 C:\MyPythonScripts\script.py "%artist%"
> 
> python27 "C:\MyPythonScripts\script.py""%artist%"

Still got nothing

**Comment by celroid** [comment]
I can confirm the script works now by trying it out in cmd, I can't figure out why it doesn't work in foobar though.

**Comment by MaciekBaron** [comment]
Have you tried looking at the Foobar Console? Is it complaining about anything?

**Comment by celroid** [comment]
![d973d2aa54baa2653cc57b24d873dcc6](https://cloud.githubusercontent.com/assets/18095088/18758538/2606d1e2-8101-11e6-8249-3de72a6c362e.png)

Thanks for helping me out, It shows it's failing.
Any ideas how to fix it? trying out that same line from the console works in cmd, .gif below.
![97d874182b55716e3853203217b2172e](https://cloud.githubusercontent.com/assets/18095088/18758703/ce2333f2-8101-11e6-8e8a-bc0077aac013.gif)

**Comment by MaciekBaron** [comment]
Perhaps python is not in your `PATH`?

Have a look here: http://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-7

**Comment by celroid** [comment]
I created a new variable called PYTHONPATH and also did it the way I used to 
![eyj1cmwioijodhrwczovl2kuz3lhem8uy29tl3rodw1ilzeymdavx2m0odc3nmyzymmyyjq3zdqyzmm3ngvmnjmzntrmywfklxbuzy5qcgcifq](https://cloud.githubusercontent.com/assets/18095088/18760000/d5c142ba-8107-11e6-9fda-bc863e2c0a36.jpg)
Still getting fail in foobar2000

**Comment by MaciekBaron** [comment]
I'm curious as to why do you keep getting the `¥` symbol instead of a slash?

**Comment by celroid** [comment]
ops that's because i'm using the japanese locale. I need that to play a visual novel.

**Comment by celroid** [comment]
![f170d684d885139117ef11107b737e9a](https://cloud.githubusercontent.com/assets/18095088/18761298/04a43bbe-810d-11e6-8dbf-9d3d89166e13.png)
I thought maybe I messed up so I redid it carefully and restarted. No luck getting it to work however.

**Comment by celroid** [comment]
Fixed it by uninstalling both python 2 and 3 and then reinstalling just python 2 to test.
It works now, just need to get python 3 installed back.

**Comment by celroid** [comment]
Thanks for your help. In the end this is just an issue with python installs. I cannot install both python 2 and 3 in any way. 
cleaned paths and did a clean reinstall of first python 2 and selected the box to add to path, then installed python3, and that removed python 2 from path. If I attempt to add PYTHONPATH for python 2 manually, python just stops working.

**Comment by MaciekBaron** [comment]
I'm glad you've managed to make it work. I'll close this issue now.
